export function generateOpenAPISpec() {
  return {
    openapi: '3.0.3',
    info: {
      title: 'portfolio-rebalancing-platform-frontend API',
      version: '1.0.0',
      description: `
# portfolio-rebalancing-platform-frontend API Documentation

## Overview
Comprehensive API documentation generated by Agent Studio with screen-specific endpoints, detailed schemas, and business logic documentation.

## Authentication
All endpoints (except /api/auth/*) require JWT authentication. Include the token in the Authorization header:
\`\`\`
Authorization: Bearer <your_jwt_token>
\`\`\`

## Rate Limiting
- Authentication endpoints: 5 requests per minute
- Read operations: 100 requests per minute
- Write operations: 30 requests per minute
- Admin operations: 10 requests per minute

## Error Handling
All errors follow a consistent format with error codes for programmatic handling. See ErrorResponse schema for details.

## Pagination
List endpoints support pagination with \`page\` and \`pageSize\` query parameters. Default page size is 20, maximum is 100.

## Versioning
API version is included in the URL path (/api/v1/). Breaking changes will increment the version number.
`,
      contact: {
        name: 'API Support',
        email: 'api-support@portfolio-rebalancing-platform-frontend.com'
      },
      license: {
        name: 'MIT',
        url: 'https://opensource.org/licenses/MIT'
      }
    },
    servers: [
      { 
        url: 'http://localhost:3000', 
        description: 'Local development server' 
      },
      { 
        url: 'http://localhost:3001', 
        description: 'Local development server (alternate port)' 
      },
      { 
        url: 'https://api-staging.portfolio-rebalancing-platform-frontend.com', 
        description: 'Staging environment' 
      },
      { 
        url: 'https://api.portfolio-rebalancing-platform-frontend.com', 
        description: 'Production environment' 
      }
    ],
    paths: {
  "/api/auth/login": {
    "post": {
      "summary": "User authentication",
      "description": "User authentication\n\n### Authentication Flow\n1. Submit valid email and password\n2. Receive JWT token and user profile\n3. Include token in Authorization header for protected endpoints\n4. Token expires after 1 hour - use refresh endpoint to renew\n\n### Security Notes\n- Password must meet complexity requirements (min 8 chars, mix of letters/numbers/symbols)\n- Failed login attempts are rate-limited after 5 consecutive failures\n- Account locks after 10 failed attempts within 15 minutes\n- Use HTTPS in production to protect credentials\n\n**Associated Screen**: Login.tsx",
      "tags": [
        "Login.tsx"
      ],
      "operationId": "postApiAuthLogin",
      "requestBody": {
        "description": "Request body for auth creation. User authentication",
        "required": true,
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/AuthPostRequest"
            },
            "examples": {
              "default": {
                "summary": "Standard request example",
                "value": {
                  "email": "user@example.com",
                  "password": "SecurePassword123!"
                }
              },
              "minimal": {
                "summary": "Minimal required fields",
                "value": {
                  "email": "user@example.com",
                  "password": "password123"
                }
              },
              "complete": {
                "summary": "Complete with optional fields",
                "value": {
                  "email": "user@example.com",
                  "password": "SecurePassword123!"
                }
              }
            }
          }
        }
      },
      "responses": {
        "201": {
          "description": "auth created successfully",
          "headers": {
            "Location": {
              "description": "URI of the created resource",
              "schema": {
                "type": "string",
                "format": "uri",
                "example": "/api/auth/abc-123-def-456"
              }
            },
            "X-Request-Id": {
              "description": "Unique request identifier for tracking",
              "schema": {
                "type": "string",
                "example": "req_1a2b3c4d5e6f"
              }
            }
          },
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/AuthPostResponse"
              },
              "examples": {
                "success": {
                  "summary": "Successfully created",
                  "value": {
                    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIn0...",
                    "user": {}
                  }
                }
              }
            }
          }
        },
        "400": {
          "$ref": "#/components/responses/BadRequest"
        },
        "401": {
          "$ref": "#/components/responses/Unauthorized"
        },
        "409": {
          "$ref": "#/components/responses/Conflict"
        },
        "422": {
          "$ref": "#/components/responses/UnprocessableEntity"
        },
        "429": {
          "$ref": "#/components/responses/TooManyRequests"
        },
        "500": {
          "$ref": "#/components/responses/InternalServerError"
        },
        "503": {
          "$ref": "#/components/responses/ServiceUnavailable"
        }
      },
      "security": [
        {
          "bearerAuth": []
        }
      ],
      "x-code-samples": [
        {
          "lang": "JavaScript",
          "source": "// Using Fetch API\nconst response = await fetch('http://localhost:3000/api/auth/login', {\n  method: 'POST',\n  headers: {\n    'Content-Type': 'application/json',\n    'Authorization': 'Bearer YOUR_JWT_TOKEN'\n  },\n  body: {\n  \"email\": \"user@example.com\",\n  \"password\": \"SecurePassword123!\"\n}\n});\n\nconst data = await response.json();\nconsole.log(data);"
        },
        {
          "lang": "Shell",
          "source": "curl -X POST http://localhost:3000/api/auth/login \\\n  -H \"Content-Type: application/json\" \\\n  -H \"Authorization: Bearer YOUR_JWT_TOKEN\" \\\\\n  -d '{\"email\":\"user@example.com\",\"password\":\"SecurePassword123!\"}'"
        },
        {
          "lang": "Python",
          "source": "import requests\n\nurl = \"http://localhost:3000/api/auth/login\"\nheaders = {\n    \"Content-Type\": \"application/json\",\n    \"Authorization\": \"Bearer YOUR_JWT_TOKEN\"\n}\ndata = {\n        \"email\": \"user@example.com\",\n        \"password\": \"SecurePassword123!\"\n    }\n\nresponse = requests.post(url, json=data, headers=headers)\nprint(response.json())"
        }
      ],
      "x-rate-limit": {
        "limit": 5,
        "window": "1 minute",
        "description": "Authentication endpoints are heavily rate-limited to prevent brute force attacks"
      },
      "x-business-rules": [
        "Account locks after 10 failed login attempts within 15 minutes",
        "Locked accounts automatically unlock after 30 minutes",
        "Password must not match any of the last 5 passwords",
        "All required fields must be provided",
        "Unique constraints are enforced at database level",
        "Related entities must exist before creating associations"
      ],
      "deprecated": false
    }
  },
  "/api/auth/register": {
    "post": {
      "summary": "User registration",
      "description": "User registration\n\n### Registration Process\n1. Validate email uniqueness\n2. Hash password using bcrypt\n3. Create user record in database\n4. Send verification email (if email verification enabled)\n5. Return user profile and auth token\n\n### Validation Rules\n- Email must be valid and unique\n- Password must meet security requirements\n- All required fields must be provided\n\n### Post-Registration\n- User can immediately access protected endpoints\n- Email verification may be required for certain actions",
      "tags": [
        "Auth"
      ],
      "operationId": "postApiAuthRegister",
      "requestBody": {
        "description": "Request body for auth creation. User registration",
        "required": true,
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/AuthPostRequest"
            },
            "examples": {
              "default": {
                "summary": "Standard request example",
                "value": {
                  "email": "user@example.com",
                  "password": "SecurePassword123!",
                  "name": "John Doe"
                }
              },
              "minimal": {
                "summary": "Minimal required fields",
                "value": {
                  "email": "user@example.com",
                  "password": "password123"
                }
              },
              "complete": {
                "summary": "Complete with optional fields",
                "value": {
                  "email": "user@example.com",
                  "password": "SecurePassword123!",
                  "name": "John Doe"
                }
              }
            }
          }
        }
      },
      "responses": {
        "201": {
          "description": "auth created successfully",
          "headers": {
            "Location": {
              "description": "URI of the created resource",
              "schema": {
                "type": "string",
                "format": "uri",
                "example": "/api/auth/abc-123-def-456"
              }
            },
            "X-Request-Id": {
              "description": "Unique request identifier for tracking",
              "schema": {
                "type": "string",
                "example": "req_1a2b3c4d5e6f"
              }
            }
          },
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/AuthPostResponse"
              },
              "examples": {
                "success": {
                  "summary": "Successfully created",
                  "value": {
                    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIn0...",
                    "user": {}
                  }
                }
              }
            }
          }
        },
        "400": {
          "$ref": "#/components/responses/BadRequest"
        },
        "401": {
          "$ref": "#/components/responses/Unauthorized"
        },
        "409": {
          "$ref": "#/components/responses/Conflict"
        },
        "422": {
          "$ref": "#/components/responses/UnprocessableEntity"
        },
        "429": {
          "$ref": "#/components/responses/TooManyRequests"
        },
        "500": {
          "$ref": "#/components/responses/InternalServerError"
        },
        "503": {
          "$ref": "#/components/responses/ServiceUnavailable"
        }
      },
      "security": [
        {
          "bearerAuth": []
        }
      ],
      "x-code-samples": [
        {
          "lang": "JavaScript",
          "source": "// Using Fetch API\nconst response = await fetch('http://localhost:3000/api/auth/register', {\n  method: 'POST',\n  headers: {\n    'Content-Type': 'application/json',\n    'Authorization': 'Bearer YOUR_JWT_TOKEN'\n  },\n  body: {\n  \"email\": \"user@example.com\",\n  \"password\": \"SecurePassword123!\",\n  \"name\": \"John Doe\"\n}\n});\n\nconst data = await response.json();\nconsole.log(data);"
        },
        {
          "lang": "Shell",
          "source": "curl -X POST http://localhost:3000/api/auth/register \\\n  -H \"Content-Type: application/json\" \\\n  -H \"Authorization: Bearer YOUR_JWT_TOKEN\" \\\\\n  -d '{\"email\":\"user@example.com\",\"password\":\"SecurePassword123!\",\"name\":\"John Doe\"}'"
        },
        {
          "lang": "Python",
          "source": "import requests\n\nurl = \"http://localhost:3000/api/auth/register\"\nheaders = {\n    \"Content-Type\": \"application/json\",\n    \"Authorization\": \"Bearer YOUR_JWT_TOKEN\"\n}\ndata = {\n        \"email\": \"user@example.com\",\n        \"password\": \"SecurePassword123!\",\n        \"name\": \"John Doe\"\n    }\n\nresponse = requests.post(url, json=data, headers=headers)\nprint(response.json())"
        }
      ],
      "x-rate-limit": {
        "limit": 5,
        "window": "1 minute",
        "description": "Authentication endpoints are heavily rate-limited to prevent brute force attacks"
      },
      "x-business-rules": [
        "Email must be unique across the system",
        "Password must meet complexity requirements (8+ chars, uppercase, lowercase, number, special char)",
        "Email verification token expires after 24 hours",
        "All required fields must be provided",
        "Unique constraints are enforced at database level",
        "Related entities must exist before creating associations"
      ],
      "deprecated": false
    }
  },
  "/api/auth/logout": {
    "post": {
      "summary": "User logout",
      "description": "User logout\n\n### Resource Creation\nCreates a new auth entry with the provided data.\n\n**Validation:**\n- All required fields must be provided\n- Field formats must match schema\n- Unique constraints are enforced\n- Business rules are validated\n\n**Returns:**\n- 201: auth created successfully\n- 400: Invalid input data\n- 409: Duplicate entry (unique constraint violation)\n- 422: Validation errors\n\n**Side Effects:**\n- Resource is persisted to database\n- Related entities may be updated\n- Notifications may be triggered\n- Audit log entry created\n\n**Associated Screen**: UserMenu.tsx",
      "tags": [
        "UserMenu.tsx"
      ],
      "operationId": "postApiAuthLogout",
      "responses": {
        "201": {
          "description": "auth created successfully",
          "headers": {
            "Location": {
              "description": "URI of the created resource",
              "schema": {
                "type": "string",
                "format": "uri",
                "example": "/api/auth/abc-123-def-456"
              }
            },
            "X-Request-Id": {
              "description": "Unique request identifier for tracking",
              "schema": {
                "type": "string",
                "example": "req_1a2b3c4d5e6f"
              }
            }
          },
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/AuthPostResponse"
              },
              "examples": {
                "success": {
                  "summary": "Successfully created",
                  "value": {
                    "success": true
                  }
                }
              }
            }
          }
        },
        "400": {
          "$ref": "#/components/responses/BadRequest"
        },
        "401": {
          "$ref": "#/components/responses/Unauthorized"
        },
        "409": {
          "$ref": "#/components/responses/Conflict"
        },
        "422": {
          "$ref": "#/components/responses/UnprocessableEntity"
        },
        "429": {
          "$ref": "#/components/responses/TooManyRequests"
        },
        "500": {
          "$ref": "#/components/responses/InternalServerError"
        },
        "503": {
          "$ref": "#/components/responses/ServiceUnavailable"
        }
      },
      "security": [
        {
          "bearerAuth": []
        }
      ],
      "x-code-samples": [
        {
          "lang": "JavaScript",
          "source": "// Using Fetch API\nconst response = await fetch('http://localhost:3000/api/auth/logout', {\n  method: 'POST',\n  headers: {\n    'Content-Type': 'application/json',\n    'Authorization': 'Bearer YOUR_JWT_TOKEN'\n  }\n});\n\nconst data = await response.json();\nconsole.log(data);"
        },
        {
          "lang": "Shell",
          "source": "curl -X POST http://localhost:3000/api/auth/logout \\\n  -H \"Content-Type: application/json\" \\\n  -H \"Authorization: Bearer YOUR_JWT_TOKEN\""
        }
      ],
      "x-rate-limit": {
        "limit": 5,
        "window": "1 minute",
        "description": "Authentication endpoints are heavily rate-limited to prevent brute force attacks"
      },
      "x-business-rules": [
        "All required fields must be provided",
        "Unique constraints are enforced at database level",
        "Related entities must exist before creating associations"
      ],
      "deprecated": false
    }
  },
  "/api/auth/me": {
    "get": {
      "summary": "Get current user profile",
      "description": "Get current user profile\n\n### List Retrieval\nRetrieves a paginated list of auth items with optional filtering and sorting.\n\n**Query Parameters:**\n- `page`: Page number (default: 1)\n- `pageSize`: Items per page (default: 20, max: 100)\n- `sort`: Sort field and direction (e.g., `createdAt:desc`)\n- `search`: Search query to filter results\n- Filter by specific fields (e.g., `status=active`)\n\n**Response includes:**\n- Array of auth items\n- Pagination metadata (total pages, current page, etc.)\n- HATEOAS links for navigation\n\n**Performance:**\n- Results are cached for 5 minutes\n- Use ETags for conditional requests\n- Maximum page size is 100 to prevent server overload",
      "tags": [
        "Auth"
      ],
      "operationId": "getApiAuthMe",
      "parameters": [
        {
          "$ref": "#/components/parameters/PageParam"
        },
        {
          "$ref": "#/components/parameters/PageSizeParam"
        },
        {
          "$ref": "#/components/parameters/SortParam"
        },
        {
          "$ref": "#/components/parameters/SearchParam"
        },
        {
          "name": "startDate",
          "in": "query",
          "required": false,
          "description": "Filter results created after this date",
          "schema": {
            "type": "string",
            "format": "date",
            "example": "2024-01-01"
          }
        },
        {
          "name": "endDate",
          "in": "query",
          "required": false,
          "description": "Filter results created before this date",
          "schema": {
            "type": "string",
            "format": "date",
            "example": "2024-12-31"
          }
        }
      ],
      "responses": {
        "200": {
          "description": "Successfully retrieved auth",
          "headers": {
            "X-Request-Id": {
              "description": "Unique request identifier for tracking",
              "schema": {
                "type": "string",
                "example": "req_1a2b3c4d5e6f"
              }
            },
            "ETag": {
              "description": "Entity tag for cache validation",
              "schema": {
                "type": "string",
                "example": "\"abc123def456\""
              }
            },
            "Cache-Control": {
              "description": "Caching directives",
              "schema": {
                "type": "string",
                "example": "public, max-age=300"
              }
            }
          },
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/AuthGetResponse"
              },
              "examples": {
                "success": {
                  "summary": "Success example",
                  "value": {
                    "user": {}
                  }
                }
              }
            }
          }
        },
        "400": {
          "$ref": "#/components/responses/BadRequest"
        },
        "401": {
          "$ref": "#/components/responses/Unauthorized"
        },
        "429": {
          "$ref": "#/components/responses/TooManyRequests"
        },
        "500": {
          "$ref": "#/components/responses/InternalServerError"
        },
        "503": {
          "$ref": "#/components/responses/ServiceUnavailable"
        }
      },
      "security": [
        {
          "bearerAuth": []
        }
      ],
      "x-code-samples": [
        {
          "lang": "JavaScript",
          "source": "// Using Fetch API\nconst response = await fetch('http://localhost:3000/api/auth/me', {\n  method: 'GET',\n  headers: {\n    'Content-Type': 'application/json',\n    'Authorization': 'Bearer YOUR_JWT_TOKEN'\n  }\n});\n\nconst data = await response.json();\nconsole.log(data);"
        },
        {
          "lang": "Shell",
          "source": "curl -X GET http://localhost:3000/api/auth/me \\\n  -H \"Content-Type: application/json\" \\\n  -H \"Authorization: Bearer YOUR_JWT_TOKEN\""
        }
      ],
      "x-rate-limit": {
        "limit": 5,
        "window": "1 minute",
        "description": "Authentication endpoints are heavily rate-limited to prevent brute force attacks"
      },
      "x-business-rules": [
        "Results are paginated with default page size of 20",
        "Maximum page size is 100 to prevent server overload",
        "Search queries are case-insensitive",
        "Results are cached for 5 minutes"
      ],
      "deprecated": false
    }
  },
  "/api/dashboard/stats": {
    "get": {
      "summary": "Fetch dashboard statistics",
      "description": "Fetch dashboard statistics\n\n### List Retrieval\nRetrieves a paginated list of dashboard items with optional filtering and sorting.\n\n**Query Parameters:**\n- `page`: Page number (default: 1)\n- `pageSize`: Items per page (default: 20, max: 100)\n- `sort`: Sort field and direction (e.g., `createdAt:desc`)\n- `search`: Search query to filter results\n- Filter by specific fields (e.g., `status=active`)\n\n**Response includes:**\n- Array of dashboard items\n- Pagination metadata (total pages, current page, etc.)\n- HATEOAS links for navigation\n\n**Performance:**\n- Results are cached for 5 minutes\n- Use ETags for conditional requests\n- Maximum page size is 100 to prevent server overload\n\n**Associated Screen**: ComplianceDashboard.tsx",
      "tags": [
        "ComplianceDashboard.tsx"
      ],
      "operationId": "getApiDashboardStats",
      "parameters": [
        {
          "$ref": "#/components/parameters/PageParam"
        },
        {
          "$ref": "#/components/parameters/PageSizeParam"
        },
        {
          "$ref": "#/components/parameters/SortParam"
        },
        {
          "$ref": "#/components/parameters/SearchParam"
        },
        {
          "name": "startDate",
          "in": "query",
          "required": false,
          "description": "Filter results created after this date",
          "schema": {
            "type": "string",
            "format": "date",
            "example": "2024-01-01"
          }
        },
        {
          "name": "endDate",
          "in": "query",
          "required": false,
          "description": "Filter results created before this date",
          "schema": {
            "type": "string",
            "format": "date",
            "example": "2024-12-31"
          }
        }
      ],
      "responses": {
        "200": {
          "description": "Successfully retrieved dashboard",
          "headers": {
            "X-Request-Id": {
              "description": "Unique request identifier for tracking",
              "schema": {
                "type": "string",
                "example": "req_1a2b3c4d5e6f"
              }
            },
            "ETag": {
              "description": "Entity tag for cache validation",
              "schema": {
                "type": "string",
                "example": "\"abc123def456\""
              }
            },
            "Cache-Control": {
              "description": "Caching directives",
              "schema": {
                "type": "string",
                "example": "public, max-age=300"
              }
            }
          },
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/DashboardGetResponse"
              },
              "examples": {
                "success": {
                  "summary": "Success example",
                  "value": {
                    "stats": {}
                  }
                }
              }
            }
          }
        },
        "400": {
          "$ref": "#/components/responses/BadRequest"
        },
        "401": {
          "$ref": "#/components/responses/Unauthorized"
        },
        "404": {
          "$ref": "#/components/responses/NotFound"
        },
        "429": {
          "$ref": "#/components/responses/TooManyRequests"
        },
        "500": {
          "$ref": "#/components/responses/InternalServerError"
        },
        "503": {
          "$ref": "#/components/responses/ServiceUnavailable"
        }
      },
      "security": [
        {
          "bearerAuth": []
        }
      ],
      "x-code-samples": [
        {
          "lang": "JavaScript",
          "source": "// Using Fetch API\nconst response = await fetch('http://localhost:3000/api/dashboard/stats', {\n  method: 'GET',\n  headers: {\n    'Content-Type': 'application/json',\n    'Authorization': 'Bearer YOUR_JWT_TOKEN'\n  }\n});\n\nconst data = await response.json();\nconsole.log(data);"
        },
        {
          "lang": "Shell",
          "source": "curl -X GET http://localhost:3000/api/dashboard/stats \\\n  -H \"Content-Type: application/json\" \\\n  -H \"Authorization: Bearer YOUR_JWT_TOKEN\""
        }
      ],
      "x-rate-limit": {
        "limit": 100,
        "window": "1 minute",
        "description": "Read operations have higher rate limits"
      },
      "x-business-rules": [
        "Results are paginated with default page size of 20",
        "Maximum page size is 100 to prevent server overload",
        "Search queries are case-insensitive",
        "Results are cached for 5 minutes"
      ],
      "deprecated": false
    }
  },
  "/api/health": {
    "get": {
      "summary": "Health check endpoint",
      "description": "Health check endpoint\n\n### List Retrieval\nRetrieves a paginated list of health items with optional filtering and sorting.\n\n**Query Parameters:**\n- `page`: Page number (default: 1)\n- `pageSize`: Items per page (default: 20, max: 100)\n- `sort`: Sort field and direction (e.g., `createdAt:desc`)\n- `search`: Search query to filter results\n- Filter by specific fields (e.g., `status=active`)\n\n**Response includes:**\n- Array of health items\n- Pagination metadata (total pages, current page, etc.)\n- HATEOAS links for navigation\n\n**Performance:**\n- Results are cached for 5 minutes\n- Use ETags for conditional requests\n- Maximum page size is 100 to prevent server overload",
      "tags": [
        "Health"
      ],
      "operationId": "getApiHealth",
      "parameters": [
        {
          "$ref": "#/components/parameters/PageParam"
        },
        {
          "$ref": "#/components/parameters/PageSizeParam"
        },
        {
          "$ref": "#/components/parameters/SortParam"
        },
        {
          "$ref": "#/components/parameters/SearchParam"
        },
        {
          "name": "startDate",
          "in": "query",
          "required": false,
          "description": "Filter results created after this date",
          "schema": {
            "type": "string",
            "format": "date",
            "example": "2024-01-01"
          }
        },
        {
          "name": "endDate",
          "in": "query",
          "required": false,
          "description": "Filter results created before this date",
          "schema": {
            "type": "string",
            "format": "date",
            "example": "2024-12-31"
          }
        }
      ],
      "responses": {
        "200": {
          "description": "Successfully retrieved health",
          "headers": {
            "X-Request-Id": {
              "description": "Unique request identifier for tracking",
              "schema": {
                "type": "string",
                "example": "req_1a2b3c4d5e6f"
              }
            },
            "ETag": {
              "description": "Entity tag for cache validation",
              "schema": {
                "type": "string",
                "example": "\"abc123def456\""
              }
            },
            "Cache-Control": {
              "description": "Caching directives",
              "schema": {
                "type": "string",
                "example": "public, max-age=300"
              }
            }
          },
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/HealthGetResponse"
              },
              "examples": {
                "success": {
                  "summary": "Success example",
                  "value": {
                    "status": "active",
                    "uptime": "2026-06-14T11:33:25.052Z",
                    "timestamp": "2026-06-14T11:33:25.052Z"
                  }
                }
              }
            }
          }
        },
        "400": {
          "$ref": "#/components/responses/BadRequest"
        },
        "401": {
          "$ref": "#/components/responses/Unauthorized"
        },
        "404": {
          "$ref": "#/components/responses/NotFound"
        },
        "429": {
          "$ref": "#/components/responses/TooManyRequests"
        },
        "500": {
          "$ref": "#/components/responses/InternalServerError"
        },
        "503": {
          "$ref": "#/components/responses/ServiceUnavailable"
        }
      },
      "security": [
        {
          "bearerAuth": []
        }
      ],
      "x-code-samples": [
        {
          "lang": "JavaScript",
          "source": "// Using Fetch API\nconst response = await fetch('http://localhost:3000/api/health', {\n  method: 'GET',\n  headers: {\n    'Content-Type': 'application/json',\n    'Authorization': 'Bearer YOUR_JWT_TOKEN'\n  }\n});\n\nconst data = await response.json();\nconsole.log(data);"
        },
        {
          "lang": "Shell",
          "source": "curl -X GET http://localhost:3000/api/health \\\n  -H \"Content-Type: application/json\" \\\n  -H \"Authorization: Bearer YOUR_JWT_TOKEN\""
        }
      ],
      "x-rate-limit": {
        "limit": 100,
        "window": "1 minute",
        "description": "Read operations have higher rate limits"
      },
      "x-business-rules": [
        "Results are paginated with default page size of 20",
        "Maximum page size is 100 to prevent server overload",
        "Search queries are case-insensitive",
        "Results are cached for 5 minutes"
      ],
      "deprecated": false
    }
  },
  "/api/clients/rebalancing-status": {
    "get": {
      "summary": "Get clients rebalancing status",
      "description": "Returns rebalancing urgency and drift data for all clients. Used by Dashboard, Compliance, and Portfolio screens.\n\n**Associated Screens**: Dashboard.tsx, CompliancePage.tsx, PortfolioClientIdPage.tsx",
      "tags": ["Dashboard.tsx", "CompliancePage.tsx", "PortfolioClientIdPage.tsx"],
      "operationId": "getApiClientsRebalancingStatus",
      "parameters": [],
      "responses": {
        "200": {
          "description": "Successfully retrieved rebalancing status",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "success": { "type": "boolean", "example": true },
                  "data": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "id": { "type": "string", "example": "CL-001" },
                        "name": { "type": "string", "example": "Sarah Thompson" },
                        "ticker": { "type": "string", "example": "SARAH-T" },
                        "value": { "type": "number", "example": 500000 },
                        "portfolioDrift": { "type": "number", "example": 2.3 },
                        "lastReview": { "type": "string", "format": "date", "example": "2025-03-15" },
                        "riskProfile": { "type": "string", "example": "Moderate" },
                        "status": { "type": "string", "example": "Active" }
                      }
                    }
                  },
                  "count": { "type": "integer", "example": 4 },
                  "timestamp": { "type": "string", "format": "date-time", "example": "2026-06-14T12:00:00Z" }
                }
              }
            }
          }
        },
        "401": { "$ref": "#/components/responses/Unauthorized" },
        "500": { "$ref": "#/components/responses/InternalServerError" }
      },
      "security": [{ "bearerAuth": [] }]
    }
  },
  "/api/proposals": {
    "get": {
      "summary": "Fetch proposals for compliance review",
      "description": "Returns a list of rebalancing proposals pending compliance review.\n\n**Associated Screen**: CompliancePage.tsx",
      "tags": ["CompliancePage.tsx"],
      "operationId": "getApiProposals",
      "parameters": [
        { "$ref": "#/components/parameters/PageParam" },
        { "$ref": "#/components/parameters/PageSizeParam" }
      ],
      "responses": {
        "200": {
          "description": "List of proposals",
          "content": {
            "application/json": {
              "schema": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "proposalId": { "type": "string", "example": "prop-456" },
                    "clientId": { "type": "string", "example": "client-123" },
                    "status": { "type": "string", "enum": ["pending", "approved", "rejected"], "example": "pending" },
                    "createdAt": { "type": "string", "format": "date-time" }
                  }
                }
              }
            }
          }
        },
        "401": { "$ref": "#/components/responses/Unauthorized" },
        "500": { "$ref": "#/components/responses/InternalServerError" }
      },
      "security": [{ "bearerAuth": [] }]
    },
    "post": {
      "summary": "Create rebalancing proposal",
      "description": "Creates a new rebalancing proposal for a client.\n\n**Associated Screen**: ProposalNewClientIdPage.tsx",
      "tags": ["ProposalNewClientIdPage.tsx"],
      "operationId": "postApiProposals",
      "requestBody": {
        "required": true,
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "required": ["clientId"],
              "properties": {
                "clientId": { "type": "string", "example": "client-123" },
                "notes": { "type": "string", "example": "Drift exceeds 5% threshold" }
              }
            }
          }
        }
      },
      "responses": {
        "201": {
          "description": "Proposal created",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "proposalId": { "type": "string", "example": "prop-456" },
                  "status": { "type": "string", "example": "pending" }
                }
              }
            }
          }
        },
        "400": { "$ref": "#/components/responses/BadRequest" },
        "401": { "$ref": "#/components/responses/Unauthorized" },
        "500": { "$ref": "#/components/responses/InternalServerError" }
      },
      "security": [{ "bearerAuth": [] }]
    }
  },
  "/api/proposals/{proposalId}": {
    "get": {
      "summary": "Fetch proposal details",
      "description": "Returns full detail of a specific rebalancing proposal.\n\n**Associated Screen**: ProposalProposalIdPage.tsx",
      "tags": ["ProposalProposalIdPage.tsx"],
      "operationId": "getApiProposalById",
      "parameters": [
        { "name": "proposalId", "in": "path", "required": true, "schema": { "type": "string" }, "example": "prop-456" }
      ],
      "responses": {
        "200": {
          "description": "Proposal detail",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "proposalId": { "type": "string" },
                  "clientId": { "type": "string" },
                  "status": { "type": "string" },
                  "trades": { "type": "array", "items": { "type": "object" } },
                  "createdAt": { "type": "string", "format": "date-time" }
                }
              }
            }
          }
        },
        "401": { "$ref": "#/components/responses/Unauthorized" },
        "404": { "$ref": "#/components/responses/NotFound" },
        "500": { "$ref": "#/components/responses/InternalServerError" }
      },
      "security": [{ "bearerAuth": [] }]
    },
    "put": {
      "summary": "Update proposal status",
      "description": "Updates the status or content of an existing proposal.\n\n**Associated Screen**: ProposalProposalIdPage.tsx",
      "tags": ["ProposalProposalIdPage.tsx"],
      "operationId": "putApiProposalById",
      "parameters": [
        { "name": "proposalId", "in": "path", "required": true, "schema": { "type": "string" }, "example": "prop-456" }
      ],
      "requestBody": {
        "required": true,
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "status": { "type": "string", "enum": ["pending", "approved", "rejected"] },
                "notes": { "type": "string" }
              }
            }
          }
        }
      },
      "responses": {
        "200": {
          "description": "Proposal updated",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "proposalId": { "type": "string" },
                  "status": { "type": "string" }
                }
              }
            }
          }
        },
        "400": { "$ref": "#/components/responses/BadRequest" },
        "401": { "$ref": "#/components/responses/Unauthorized" },
        "404": { "$ref": "#/components/responses/NotFound" },
        "500": { "$ref": "#/components/responses/InternalServerError" }
      },
      "security": [{ "bearerAuth": [] }]
    }
  },
  "/api/proposals/{proposalId}/approve": {
    "put": {
      "summary": "Approve or reject proposal",
      "description": "Approves or rejects a rebalancing proposal after compliance review.\n\n**Associated Screen**: CompliancePage.tsx",
      "tags": ["CompliancePage.tsx"],
      "operationId": "putApiProposalApprove",
      "parameters": [
        { "name": "proposalId", "in": "path", "required": true, "schema": { "type": "string" }, "example": "prop-456" }
      ],
      "requestBody": {
        "required": true,
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "required": ["decision"],
              "properties": {
                "decision": { "type": "string", "enum": ["approved", "rejected"], "example": "approved" },
                "reason": { "type": "string", "example": "Meets drift threshold policy" }
              }
            }
          }
        }
      },
      "responses": {
        "200": {
          "description": "Decision recorded",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "proposalId": { "type": "string" },
                  "decision": { "type": "string" },
                  "updatedAt": { "type": "string", "format": "date-time" }
                }
              }
            }
          }
        },
        "400": { "$ref": "#/components/responses/BadRequest" },
        "401": { "$ref": "#/components/responses/Unauthorized" },
        "404": { "$ref": "#/components/responses/NotFound" },
        "500": { "$ref": "#/components/responses/InternalServerError" }
      },
      "security": [{ "bearerAuth": [] }]
    }
  },
  "/api/audit/logs": {
    "get": {
      "summary": "Fetch audit trail logs",
      "description": "Returns paginated audit trail events for compliance and regulatory tracking.\n\n**Associated Screen**: AuditPage.tsx",
      "tags": ["AuditPage.tsx"],
      "operationId": "getApiAuditLogs",
      "parameters": [
        { "$ref": "#/components/parameters/PageParam" },
        { "$ref": "#/components/parameters/PageSizeParam" },
        { "name": "startDate", "in": "query", "required": false, "schema": { "type": "string", "format": "date" }, "example": "2026-01-01" },
        { "name": "endDate", "in": "query", "required": false, "schema": { "type": "string", "format": "date" }, "example": "2026-12-31" },
        { "name": "userId", "in": "query", "required": false, "schema": { "type": "string" }, "description": "Filter by user who performed the action" }
      ],
      "responses": {
        "200": {
          "description": "Audit log entries",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "logs": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "logId": { "type": "string" },
                        "action": { "type": "string", "example": "PROPOSAL_APPROVED" },
                        "userId": { "type": "string" },
                        "timestamp": { "type": "string", "format": "date-time" },
                        "details": { "type": "object" }
                      }
                    }
                  },
                  "total": { "type": "integer" },
                  "page": { "type": "integer" }
                }
              }
            }
          }
        },
        "401": { "$ref": "#/components/responses/Unauthorized" },
        "500": { "$ref": "#/components/responses/InternalServerError" }
      },
      "security": [{ "bearerAuth": [] }]
    }
  }
},
    components: {
      schemas: {
  "AuthPostRequest": {
    "type": "object",
    "properties": {
      "email": {
        "type": "string",
        "description": "User email address",
        "format": "email",
        "example": "user@example.com"
      },
      "password": {
        "type": "string",
        "description": "User password",
        "format": "password",
        "example": "SecurePass123!"
      },
      "name": {
        "type": "string",
        "description": "name of the entity",
        "example": "John Doe"
      }
    },
    "required": [
      "email",
      "password",
      "name"
    ]
  },
  "AuthPostResponse": {
    "type": "object",
    "properties": {
      "success": {
        "type": "boolean",
        "description": "Operation success status",
        "example": true
      }
    }
  },
  "AuthGetResponse": {
    "type": "object",
    "properties": {
      "user": {
        "type": "object",
        "description": "user field",
        "example": {}
      }
    }
  },
  "DashboardGetResponse": {
    "type": "object",
    "properties": {
      "stats": {
        "type": "object",
        "description": "stats field",
        "example": {}
      }
    }
  },
  "HealthGetResponse": {
    "type": "object",
    "properties": {
      "status": {
        "type": "string",
        "description": "Status indicator",
        "enum": [
          "active",
          "inactive",
          "pending",
          "completed"
        ],
        "example": "active"
      },
      "uptime": {
        "type": "number",
        "description": "Date/time value",
        "format": "date-time",
        "example": "2026-06-14T11:33:25.051Z"
      },
      "timestamp": {
        "type": "number",
        "description": "Date/time value",
        "format": "date-time",
        "example": "2026-06-14T11:33:25.051Z"
      }
    }
  },
  "ErrorResponse": {
    "type": "object",
    "required": [
      "error",
      "code",
      "timestamp"
    ],
    "properties": {
      "error": {
        "type": "string",
        "description": "Human-readable error message",
        "example": "Invalid request data"
      },
      "code": {
        "type": "string",
        "description": "Machine-readable error code for programmatic handling",
        "example": "VALIDATION_ERROR",
        "enum": [
          "VALIDATION_ERROR",
          "AUTHENTICATION_REQUIRED",
          "AUTHORIZATION_FAILED",
          "RESOURCE_NOT_FOUND",
          "DUPLICATE_ENTRY",
          "RATE_LIMIT_EXCEEDED",
          "INTERNAL_SERVER_ERROR",
          "SERVICE_UNAVAILABLE"
        ]
      },
      "timestamp": {
        "type": "string",
        "format": "date-time",
        "description": "ISO 8601 timestamp when error occurred",
        "example": "2026-06-14T11:33:25.054Z"
      },
      "details": {
        "type": "object",
        "description": "Additional error context and field-specific validation errors",
        "additionalProperties": true,
        "example": {
          "email": "Invalid email format",
          "password": "Must be at least 8 characters"
        }
      },
      "requestId": {
        "type": "string",
        "description": "Unique request identifier for tracking and debugging",
        "example": "req_1a2b3c4d5e6f"
      },
      "path": {
        "type": "string",
        "description": "API endpoint path where error occurred",
        "example": "/api/auth/login"
      }
    }
  },
  "ValidationErrorResponse": {
    "type": "object",
    "required": [
      "error",
      "code",
      "validationErrors"
    ],
    "properties": {
      "error": {
        "type": "string",
        "description": "Error message",
        "example": "Validation failed for one or more fields"
      },
      "code": {
        "type": "string",
        "description": "Error code",
        "example": "VALIDATION_ERROR"
      },
      "validationErrors": {
        "type": "array",
        "description": "List of field validation errors",
        "items": {
          "type": "object",
          "properties": {
            "field": {
              "type": "string",
              "description": "Field name that failed validation",
              "example": "email"
            },
            "message": {
              "type": "string",
              "description": "Validation error message",
              "example": "Email must be a valid email address"
            },
            "rule": {
              "type": "string",
              "description": "Validation rule that failed",
              "example": "email"
            },
            "value": {
              "type": "string",
              "description": "The value that failed validation",
              "example": "invalid-email"
            }
          }
        }
      },
      "timestamp": {
        "type": "string",
        "format": "date-time",
        "example": "2026-06-14T11:33:25.054Z"
      }
    }
  },
  "PaginationMeta": {
    "type": "object",
    "description": "Pagination metadata for list responses",
    "properties": {
      "page": {
        "type": "number",
        "description": "Current page number (1-indexed)",
        "example": 1,
        "minimum": 1
      },
      "pageSize": {
        "type": "number",
        "description": "Number of items per page",
        "example": 20,
        "minimum": 1,
        "maximum": 100
      },
      "totalPages": {
        "type": "number",
        "description": "Total number of pages available",
        "example": 5
      },
      "totalItems": {
        "type": "number",
        "description": "Total number of items across all pages",
        "example": 97
      },
      "hasNextPage": {
        "type": "boolean",
        "description": "Whether there is a next page available",
        "example": true
      },
      "hasPreviousPage": {
        "type": "boolean",
        "description": "Whether there is a previous page available",
        "example": false
      },
      "links": {
        "type": "object",
        "description": "HATEOAS links for pagination navigation",
        "properties": {
          "self": {
            "type": "string",
            "format": "uri",
            "example": "/api/users?page=1&pageSize=20"
          },
          "first": {
            "type": "string",
            "format": "uri",
            "example": "/api/users?page=1&pageSize=20"
          },
          "last": {
            "type": "string",
            "format": "uri",
            "example": "/api/users?page=5&pageSize=20"
          },
          "next": {
            "type": "string",
            "format": "uri",
            "example": "/api/users?page=2&pageSize=20"
          },
          "prev": {
            "type": "string",
            "format": "uri",
            "nullable": true,
            "example": null
          }
        }
      }
    }
  }
},
      securitySchemes: {
        bearerAuth: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT',
          description: `
JWT token for authentication. 

**How to obtain:**
1. Call POST /api/auth/login with valid credentials
2. Extract the \`token\` from the response
3. Include in subsequent requests: \`Authorization: Bearer <token>\`

**Token expiration:**
- Access tokens expire after 1 hour
- Use POST /api/auth/refresh to obtain a new token

**Token format:**
\`\`\`
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxMjM0NTY3ODkwIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
\`\`\`
`
        },
        apiKey: {
          type: 'apiKey',
          in: 'header',
          name: 'X-API-Key',
          description: 'API key for machine-to-machine authentication. Contact support to obtain an API key.'
        }
      },
      responses: {
        BadRequest: {
          description: 'Bad Request - Invalid input data or malformed request',
          content: {
            'application/json': {
              schema: { $ref: '#/components/schemas/ErrorResponse' },
              examples: {
                validationError: {
                  summary: 'Validation error example',
                  value: {
                    error: 'Invalid request data',
                    code: 'VALIDATION_ERROR',
                    timestamp: new Date().toISOString(),
                    details: {
                      email: 'Invalid email format',
                      password: 'Must be at least 8 characters'
                    },
                    requestId: 'req_1a2b3c4d5e6f',
                    path: '/api/auth/register'
                  }
                }
              }
            }
          }
        },
        Unauthorized: {
          description: 'Unauthorized - Authentication required or token expired',
          content: {
            'application/json': {
              schema: { $ref: '#/components/schemas/ErrorResponse' },
              examples: {
                missingToken: {
                  summary: 'Missing authentication token',
                  value: {
                    error: 'Authentication required',
                    code: 'AUTHENTICATION_REQUIRED',
                    timestamp: new Date().toISOString(),
                    requestId: 'req_2b3c4d5e6f7g'
                  }
                },
                expiredToken: {
                  summary: 'Expired token',
                  value: {
                    error: 'Token has expired',
                    code: 'TOKEN_EXPIRED',
                    timestamp: new Date().toISOString(),
                    requestId: 'req_3c4d5e6f7g8h'
                  }
                }
              }
            }
          }
        },
        Forbidden: {
          description: 'Forbidden - Insufficient permissions to access this resource',
          content: {
            'application/json': {
              schema: { $ref: '#/components/schemas/ErrorResponse' },
              example: {
                error: 'You do not have permission to perform this action',
                code: 'AUTHORIZATION_FAILED',
                timestamp: new Date().toISOString(),
                requestId: 'req_4d5e6f7g8h9i'
              }
            }
          }
        },
        NotFound: {
          description: 'Not Found - The requested resource does not exist',
          content: {
            'application/json': {
              schema: { $ref: '#/components/schemas/ErrorResponse' },
              example: {
                error: 'Resource not found',
                code: 'RESOURCE_NOT_FOUND',
                timestamp: new Date().toISOString(),
                path: '/api/users/999',
                requestId: 'req_5e6f7g8h9i0j'
              }
            }
          }
        },
        Conflict: {
          description: 'Conflict - Resource already exists or conflicting operation',
          content: {
            'application/json': {
              schema: { $ref: '#/components/schemas/ErrorResponse' },
              example: {
                error: 'A user with this email already exists',
                code: 'DUPLICATE_ENTRY',
                timestamp: new Date().toISOString(),
                details: { field: 'email', value: 'user@example.com' },
                requestId: 'req_6f7g8h9i0j1k'
              }
            }
          }
        },
        UnprocessableEntity: {
          description: 'Unprocessable Entity - Validation failed for one or more fields',
          content: {
            'application/json': {
              schema: { $ref: '#/components/schemas/ValidationErrorResponse' }
            }
          }
        },
        TooManyRequests: {
          description: 'Too Many Requests - Rate limit exceeded',
          headers: {
            'X-RateLimit-Limit': {
              description: 'The maximum number of requests allowed in the time window',
              schema: { type: 'integer', example: 100 }
            },
            'X-RateLimit-Remaining': {
              description: 'The number of requests remaining in the current window',
              schema: { type: 'integer', example: 0 }
            },
            'X-RateLimit-Reset': {
              description: 'Unix timestamp when the rate limit resets',
              schema: { type: 'integer', example: 1640995200 }
            },
            'Retry-After': {
              description: 'Number of seconds until rate limit resets',
              schema: { type: 'integer', example: 60 }
            }
          },
          content: {
            'application/json': {
              schema: { $ref: '#/components/schemas/ErrorResponse' },
              example: {
                error: 'Rate limit exceeded. Please try again later.',
                code: 'RATE_LIMIT_EXCEEDED',
                timestamp: new Date().toISOString(),
                details: {
                  limit: 100,
                  remaining: 0,
                  resetAt: new Date(Date.now() + 60000).toISOString()
                },
                requestId: 'req_7g8h9i0j1k2l'
              }
            }
          }
        },
        InternalServerError: {
          description: 'Internal Server Error - An unexpected error occurred',
          content: {
            'application/json': {
              schema: { $ref: '#/components/schemas/ErrorResponse' },
              example: {
                error: 'An unexpected error occurred. Please try again later.',
                code: 'INTERNAL_SERVER_ERROR',
                timestamp: new Date().toISOString(),
                requestId: 'req_8h9i0j1k2l3m'
              }
            }
          }
        },
        ServiceUnavailable: {
          description: 'Service Unavailable - The server is temporarily unable to handle the request',
          content: {
            'application/json': {
              schema: { $ref: '#/components/schemas/ErrorResponse' },
              example: {
                error: 'Service temporarily unavailable. Please try again later.',
                code: 'SERVICE_UNAVAILABLE',
                timestamp: new Date().toISOString(),
                requestId: 'req_9i0j1k2l3m4n'
              }
            }
          }
        }
      },
      parameters: {
        PageParam: {
          name: 'page',
          in: 'query',
          description: 'Page number for pagination (1-indexed)',
          required: false,
          schema: {
            type: 'integer',
            minimum: 1,
            default: 1,
            example: 1
          }
        },
        PageSizeParam: {
          name: 'pageSize',
          in: 'query',
          description: 'Number of items per page',
          required: false,
          schema: {
            type: 'integer',
            minimum: 1,
            maximum: 100,
            default: 20,
            example: 20
          }
        },
        SortParam: {
          name: 'sort',
          in: 'query',
          description: 'Sort field and direction (e.g., createdAt:desc, name:asc)',
          required: false,
          schema: {
            type: 'string',
            pattern: '^[a-zA-Z]+:(asc|desc)$',
            example: 'createdAt:desc'
          }
        },
        SearchParam: {
          name: 'search',
          in: 'query',
          description: 'Search query to filter results',
          required: false,
          schema: {
            type: 'string',
            minLength: 1,
            example: 'john'
          }
        }
      }
    }
  };
}
